spring.application.name=lablens-backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# monday.com
lablens.monday.api-token=${MONDAY_API_TOKEN}
lablens.monday.board-id=${MONDAY_BOARD_ID}
lablens.monday.assignee-column-id=${MONDAY_ASSIGNEE_COLUMN_ID}

# Allowed monday.com display columns
lablens.monday.sample-name-column-id=${MONDAY_SAMPLE_NAME_COLUMN_ID}
lablens.monday.analyst-due-column-id=${MONDAY_ANALYST_DUE_COLUMN_ID}
lablens.monday.status-column-id=${MONDAY_STATUS_COLUMN_ID}
lablens.monday.tat-column-id=${MONDAY_TAT_COLUMN_ID}
lablens.monday.queue-status-column-id=${MONDAY_QUEUE_STATUS_COLUMN_ID}